version: '3.4'
services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - api
      - web
    links:
      - api
    ports:
      - "8080:80"
    volumes:
      - shared:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
  api:
    build: 
      context: ../simbad-pipeline-server
      dockerfile: ./docker/Dockerfile
    image: simbad-pipeline-server
    container_name: simbad-pipeline-server-api
    command: python entrypoint_api.py --port 8081 --debug
    env_file:
     - ./docker.env
    ports:
      - "8081:8081"
    volumes:
      - .:/app/
  worker:
    build:
      context: ../simbad-pipeline-server
      dockerfile: ./docker/Dockerfile
    image: simbad-pipeline-server-worker
    container_name: some_worker
    depends_on:
      - redis
    command: celery worker -A entrypoint_celery.celery --loglevel=info
    env_file:
     - ./docker.env
    volumes:
      - .:/app/
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  web:
    image: simbad-client
    container_name: simbad-client
    build:
      context: ../simbad-client
      dockerfile: ./docker/simbad-production.Dockerfile
      target: production
    volumes:
      - shared:/usr/simbad-client/app
volumes:
  shared: {}
