version: '3.4'
services:
  pipeline:
    build:
      context: ../simbad-pipeline-server
      dockerfile: ./docker/Dockerfile
    image: simbad-pipeline-server
    container_name: simbad-pipeline-server
    command: python entrypoint_api.py --port 8081 --debug
    env_file:
      - ./docker.env
    ports:
      - "8081:8081"
    volumes:
      - ../data:/usr/data
#      - sshfs:/usr/sshfs
    depends_on:
      - redis
  worker:
    build:
      context: ../simbad-pipeline-server
      dockerfile: ./docker/Dockerfile
    image: simbad-pipeline-server-worker
    container_name: celery-worker
    links:
      - analyzer-server
    depends_on:
      - redis
    command: celery worker -A entrypoint_celery.celery --loglevel=info
    env_file:
      - ./docker.env
    volumes:
      - ../data:/usr/data
#      - sshfs:/usr/sshfs
  analyzer-server:
    build:
      context: ../simbad-analyzer-server
      dockerfile: ./docker/Dockerfile
    image: simbad-analyzer-server
    container_name: simbad-analyzer-server
    command: python3 app.py --port 5000 --debug
    env_file:
      - ./docker.env
    volumes:
      - ../data:/usr/data
      - ./log4j.properties:/opt/spark-2.4.3-bin-hadoop2.7/conf/log4j.properties
#      - sshfs:/usr/sshfs
    depends_on:
      - redis
    ports:
      - "5000:5000"
      - "4040:4040"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  client:
    image: simbad-client-nginx
    container_name: simbad-client-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    build:
      context: ../simbad-client
      dockerfile: ./docker/simbad-production.Dockerfile
    network_mode: host

volumes:
  sshfs:
    name: sshfs
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "pi@192.168.0.32:/home/pi/simbad/data"
      password: "simbadcore"
